package com.ielliena.genshinquestion;

public class Array {

    final int[] questions_venti = {
            R.string.question_venti_1,
            R.string.question_venti_2,
            R.string.question_venti_3,
            R.string.question_venti_4,
            R.string.question_venti_5,
            R.string.question_venti_6,
            R.string.question_venti_7,
            R.string.question_venti_8,
            R.string.question_venti_9,
            R.string.question_venti_10,
            R.string.question_venti_11,
            R.string.question_venti_12,
            R.string.question_venti_13,
            R.string.question_venti_14,
            R.string.question_venti_15,
            R.string.question_venti_16,
            R.string.question_venti_17
    };

    final int[][] answers_venti = {{
            R.string.question_venti_1_1,
            R.string.question_venti_1_2,
            R.string.question_venti_1_3,
            R.string.question_venti_1_4
    },{
            R.string.question_venti_2_1,
            R.string.question_venti_2_2,
            R.string.question_venti_2_3,
            R.string.question_venti_2_4
    },{
            R.string.question_venti_3_1,
            R.string.question_venti_3_2,
            R.string.question_venti_3_3,
            R.string.question_venti_3_4
    },{
            R.string.question_venti_4_1,
            R.string.question_venti_4_2,
            R.string.question_venti_4_3,
            R.string.question_venti_4_4
    },{
            R.string.question_venti_5_1,
            R.string.question_venti_5_2,
            R.string.question_venti_5_3,
            R.string.question_venti_5_4
    },{
            R.string.question_venti_6_1,
            R.string.question_venti_6_2,
            R.string.question_venti_6_3,
            R.string.question_venti_6_4
    },{
            R.string.question_venti_7_1,
            R.string.question_venti_7_2,
            R.string.question_venti_7_3,
            R.string.question_venti_7_4
    },{
            R.string.question_venti_8_1,
            R.string.question_venti_8_2,
            R.string.question_venti_8_3,
            R.string.question_venti_8_4
    },{
            R.string.question_venti_9_1,
            R.string.question_venti_9_2,
            R.string.question_venti_9_3,
            R.string.question_venti_9_4
    },{
            R.string.question_venti_10_1,
            R.string.question_venti_10_2,
            R.string.question_venti_10_3,
            R.string.question_venti_10_4
    },{
            R.string.question_venti_11_1,
            R.string.question_venti_11_2,
            R.string.question_venti_11_3,
            R.string.question_venti_11_4
    },{
            R.string.question_venti_12_1,
            R.string.question_venti_12_2,
            R.string.question_venti_12_3,
            R.string.question_venti_12_4
    },{
            R.string.question_venti_13_1,
            R.string.question_venti_13_2,
            R.string.question_venti_13_3,
            R.string.question_venti_13_4
    },{
            R.string.question_venti_14_1,
            R.string.question_venti_14_2,
            R.string.question_venti_14_3,
            R.string.question_venti_14_4
    },{
            R.string.question_venti_15_1,
            R.string.question_venti_15_2,
            R.string.question_venti_15_3,
            R.string.question_venti_15_4
    },{
            R.string.question_venti_16_1,
            R.string.question_venti_16_2,
            R.string.question_venti_16_3,
            R.string.question_venti_16_4
    },{
            R.string.question_venti_17_1,
            R.string.question_venti_17_2,
            R.string.question_venti_17_3,
            R.string.question_venti_17_4
    }};

    final int[] questions_barbara = {
            R.string.question_barbara_1,
            R.string.question_barbara_2,
            R.string.question_barbara_3,
            R.string.question_barbara_4,
            R.string.question_barbara_5,
            R.string.question_barbara_6,
            R.string.question_barbara_7,
            R.string.question_barbara_8,
            R.string.question_barbara_9,
            R.string.question_barbara_10,
            R.string.question_barbara_11,
            R.string.question_barbara_12,
            R.string.question_barbara_13,
            R.string.question_barbara_14,
            R.string.question_barbara_15,
            R.string.question_barbara_16,
            R.string.question_barbara_17
    };

    final int[][] answers_barbara = {{
            R.string.question_barbara_1_1,
            R.string.question_barbara_1_2,
            R.string.question_barbara_1_3,
            R.string.question_barbara_1_4
    },{
            R.string.question_barbara_2_1,
            R.string.question_barbara_2_2,
            R.string.question_barbara_2_3,
            R.string.question_barbara_2_4
    },{
            R.string.question_barbara_3_1,
            R.string.question_barbara_3_2,
            R.string.question_barbara_3_3,
            R.string.question_barbara_3_4
    },{
            R.string.question_barbara_4_1,
            R.string.question_barbara_4_2,
            R.string.question_barbara_4_3,
            R.string.question_barbara_4_4
    },{
            R.string.question_barbara_5_1,
            R.string.question_barbara_5_2,
            R.string.question_barbara_5_3,
            R.string.question_barbara_5_4
    },{
            R.string.question_barbara_6_1,
            R.string.question_barbara_6_2,
            R.string.question_barbara_6_3,
            R.string.question_barbara_6_4
    },{
            R.string.question_barbara_7_1,
            R.string.question_barbara_7_2,
            R.string.question_barbara_7_3,
            R.string.question_barbara_7_4
    },{
            R.string.question_barbara_8_1,
            R.string.question_barbara_8_2,
            R.string.question_barbara_8_3,
            R.string.question_barbara_8_4
    },{
            R.string.question_barbara_9_1,
            R.string.question_barbara_9_2,
            R.string.question_barbara_9_3,
            R.string.question_barbara_9_4
    },{
            R.string.question_barbara_10_1,
            R.string.question_barbara_10_2,
            R.string.question_barbara_10_3,
            R.string.question_barbara_10_4
    },{
            R.string.question_barbara_11_1,
            R.string.question_barbara_11_2,
            R.string.question_barbara_11_3,
            R.string.question_barbara_11_4
    },{
            R.string.question_barbara_12_1,
            R.string.question_barbara_12_2,
            R.string.question_barbara_12_3,
            R.string.question_barbara_12_4
    },{
            R.string.question_barbara_13_1,
            R.string.question_barbara_13_2,
            R.string.question_barbara_13_3,
            R.string.question_barbara_13_4
    },{
            R.string.question_barbara_14_1,
            R.string.question_barbara_14_2,
            R.string.question_barbara_14_3,
            R.string.question_barbara_14_4
    },{
            R.string.question_barbara_15_1,
            R.string.question_barbara_15_2,
            R.string.question_barbara_15_3,
            R.string.question_barbara_15_4
    },{
            R.string.question_barbara_16_1,
            R.string.question_barbara_16_2,
            R.string.question_barbara_16_3,
            R.string.question_barbara_16_4
    },{
            R.string.question_barbara_17_1,
            R.string.question_barbara_17_2,
            R.string.question_barbara_17_3,
            R.string.question_barbara_17_4
    }};

    final int[] questions_diluc = {
            R.string.question_diluc_1,
            R.string.question_diluc_2,
            R.string.question_diluc_3,
            R.string.question_diluc_4,
            R.string.question_diluc_5,
            R.string.question_diluc_6,
            R.string.question_diluc_7,
            R.string.question_diluc_8,
            R.string.question_diluc_9,
            R.string.question_diluc_10,
            R.string.question_diluc_11,
            R.string.question_diluc_12,
            R.string.question_diluc_13,
            R.string.question_diluc_14,
            R.string.question_diluc_15,
            R.string.question_diluc_16,
            R.string.question_diluc_17
    };

    final int[][] answers_diluc = {{
            R.string.question_diluc_1_1,
            R.string.question_diluc_1_2,
            R.string.question_diluc_1_3,
            R.string.question_diluc_1_4
    },{
            R.string.question_diluc_2_1,
            R.string.question_diluc_2_2,
            R.string.question_diluc_2_3,
            R.string.question_diluc_2_4
    },{
            R.string.question_diluc_3_1,
            R.string.question_diluc_3_2,
            R.string.question_diluc_3_3,
            R.string.question_diluc_3_4
    },{
            R.string.question_diluc_4_1,
            R.string.question_diluc_4_2,
            R.string.question_diluc_4_3,
            R.string.question_diluc_4_4
    },{
            R.string.question_diluc_5_1,
            R.string.question_diluc_5_2,
            R.string.question_diluc_5_3,
            R.string.question_diluc_5_4
    },{
            R.string.question_diluc_6_1,
            R.string.question_diluc_6_2,
            R.string.question_diluc_6_3,
            R.string.question_diluc_6_4
    },{
            R.string.question_diluc_7_1,
            R.string.question_diluc_7_2,
            R.string.question_diluc_7_3,
            R.string.question_diluc_7_4
    },{
            R.string.question_diluc_8_1,
            R.string.question_diluc_8_2,
            R.string.question_diluc_8_3,
            R.string.question_diluc_8_4
    },{
            R.string.question_diluc_9_1,
            R.string.question_diluc_9_2,
            R.string.question_diluc_9_3,
            R.string.question_diluc_9_4
    },{
            R.string.question_diluc_10_1,
            R.string.question_diluc_10_2,
            R.string.question_diluc_10_3,
            R.string.question_diluc_10_4
    },{
            R.string.question_diluc_11_1,
            R.string.question_diluc_11_2,
            R.string.question_diluc_11_3,
            R.string.question_diluc_11_4
    },{
            R.string.question_diluc_12_1,
            R.string.question_diluc_12_2,
            R.string.question_diluc_12_3,
            R.string.question_diluc_12_4
    },{
            R.string.question_diluc_13_1,
            R.string.question_diluc_13_2,
            R.string.question_diluc_13_3,
            R.string.question_diluc_13_4
    },{
            R.string.question_diluc_14_1,
            R.string.question_diluc_14_2,
            R.string.question_diluc_14_3,
            R.string.question_diluc_14_4
    },{
            R.string.question_diluc_15_1,
            R.string.question_diluc_15_2,
            R.string.question_diluc_15_3,
            R.string.question_diluc_15_4
    },{
            R.string.question_diluc_16_1,
            R.string.question_diluc_16_2,
            R.string.question_diluc_16_3,
            R.string.question_diluc_16_4
    },{
            R.string.question_diluc_17_1,
            R.string.question_diluc_17_2,
            R.string.question_diluc_17_3,
            R.string.question_diluc_17_4
    }};

    final int[] questions_lisa = {
            R.string.question_lisa_1,
            R.string.question_lisa_2,
            R.string.question_lisa_3,
            R.string.question_lisa_4,
            R.string.question_lisa_5,
            R.string.question_lisa_6,
            R.string.question_lisa_7,
            R.string.question_lisa_8,
            R.string.question_lisa_9,
            R.string.question_lisa_10,
            R.string.question_lisa_11,
            R.string.question_lisa_12,
            R.string.question_lisa_13,
            R.string.question_lisa_14,
            R.string.question_lisa_15,
            R.string.question_lisa_16,
            R.string.question_lisa_17
    };

    final int[][] answers_lisa = {{
            R.string.question_lisa_1_1,
            R.string.question_lisa_1_2,
            R.string.question_lisa_1_3,
            R.string.question_lisa_1_4
    },{
            R.string.question_lisa_2_1,
            R.string.question_lisa_2_2,
            R.string.question_lisa_2_3,
            R.string.question_lisa_2_4
    },{
            R.string.question_lisa_3_1,
            R.string.question_lisa_3_2,
            R.string.question_lisa_3_3,
            R.string.question_lisa_3_4
    },{
            R.string.question_lisa_4_1,
            R.string.question_lisa_4_2,
            R.string.question_lisa_4_3,
            R.string.question_lisa_4_4
    },{
            R.string.question_lisa_5_1,
            R.string.question_lisa_5_2,
            R.string.question_lisa_5_3,
            R.string.question_lisa_5_4
    },{
            R.string.question_lisa_6_1,
            R.string.question_lisa_6_2,
            R.string.question_lisa_6_3,
            R.string.question_lisa_6_4
    },{
            R.string.question_lisa_7_1,
            R.string.question_lisa_7_2,
            R.string.question_lisa_7_3,
            R.string.question_lisa_7_4
    },{
            R.string.question_lisa_8_1,
            R.string.question_lisa_8_2,
            R.string.question_lisa_8_3,
            R.string.question_lisa_8_4
    },{
            R.string.question_lisa_9_1,
            R.string.question_lisa_9_2,
            R.string.question_lisa_9_3,
            R.string.question_lisa_9_4
    },{
            R.string.question_lisa_10_1,
            R.string.question_lisa_10_2,
            R.string.question_lisa_10_3,
            R.string.question_lisa_10_4
    },{
            R.string.question_lisa_11_1,
            R.string.question_lisa_11_2,
            R.string.question_lisa_11_3,
            R.string.question_lisa_11_4
    },{
            R.string.question_lisa_12_1,
            R.string.question_lisa_12_2,
            R.string.question_lisa_12_3,
            R.string.question_lisa_12_4
    },{
            R.string.question_lisa_13_1,
            R.string.question_lisa_13_2,
            R.string.question_lisa_13_3,
            R.string.question_lisa_13_4
    },{
            R.string.question_lisa_14_1,
            R.string.question_lisa_14_2,
            R.string.question_lisa_14_3,
            R.string.question_lisa_14_4
    },{
            R.string.question_lisa_15_1,
            R.string.question_lisa_15_2,
            R.string.question_lisa_15_3,
            R.string.question_lisa_15_4
    },{
            R.string.question_lisa_16_1,
            R.string.question_lisa_16_2,
            R.string.question_lisa_16_3,
            R.string.question_lisa_16_4
    },{
            R.string.question_lisa_17_1,
            R.string.question_lisa_17_2,
            R.string.question_lisa_17_3,
            R.string.question_lisa_17_4
    }};

    final int[] questions_kaeya = {
            R.string.question_kaeya_1,
            R.string.question_kaeya_2,
            R.string.question_kaeya_3,
            R.string.question_kaeya_4,
            R.string.question_kaeya_5,
            R.string.question_kaeya_6,
            R.string.question_kaeya_7,
            R.string.question_kaeya_8,
            R.string.question_kaeya_9,
            R.string.question_kaeya_10,
            R.string.question_kaeya_11,
            R.string.question_kaeya_12,
            R.string.question_kaeya_13,
            R.string.question_kaeya_14,
            R.string.question_kaeya_15,
            R.string.question_kaeya_16,
            R.string.question_kaeya_17
    };

    final int[][] answers_kaeya = {{
            R.string.question_kaeya_1_1,
            R.string.question_kaeya_1_2,
            R.string.question_kaeya_1_3,
            R.string.question_kaeya_1_4
    },{
            R.string.question_kaeya_2_1,
            R.string.question_kaeya_2_2,
            R.string.question_kaeya_2_3,
            R.string.question_kaeya_2_4
    },{
            R.string.question_kaeya_3_1,
            R.string.question_kaeya_3_2,
            R.string.question_kaeya_3_3,
            R.string.question_kaeya_3_4
    },{
            R.string.question_kaeya_4_1,
            R.string.question_kaeya_4_2,
            R.string.question_kaeya_4_3,
            R.string.question_kaeya_4_4
    },{
            R.string.question_kaeya_5_1,
            R.string.question_kaeya_5_2,
            R.string.question_kaeya_5_3,
            R.string.question_kaeya_5_4
    },{
            R.string.question_kaeya_6_1,
            R.string.question_kaeya_6_2,
            R.string.question_kaeya_6_3,
            R.string.question_kaeya_6_4
    },{
            R.string.question_kaeya_7_1,
            R.string.question_kaeya_7_2,
            R.string.question_kaeya_7_3,
            R.string.question_kaeya_7_4
    },{
            R.string.question_kaeya_8_1,
            R.string.question_kaeya_8_2,
            R.string.question_kaeya_8_3,
            R.string.question_kaeya_8_4
    },{
            R.string.question_kaeya_9_1,
            R.string.question_kaeya_9_2,
            R.string.question_kaeya_9_3,
            R.string.question_kaeya_9_4
    },{
            R.string.question_kaeya_10_1,
            R.string.question_kaeya_10_2,
            R.string.question_kaeya_10_3,
            R.string.question_kaeya_10_4
    },{
            R.string.question_kaeya_11_1,
            R.string.question_kaeya_11_2,
            R.string.question_kaeya_11_3,
            R.string.question_kaeya_11_4
    },{
            R.string.question_kaeya_12_1,
            R.string.question_kaeya_12_2,
            R.string.question_kaeya_12_3,
            R.string.question_kaeya_12_4
    },{
            R.string.question_kaeya_13_1,
            R.string.question_kaeya_13_2,
            R.string.question_kaeya_13_3,
            R.string.question_kaeya_13_4
    },{
            R.string.question_kaeya_14_1,
            R.string.question_kaeya_14_2,
            R.string.question_kaeya_14_3,
            R.string.question_kaeya_14_4
    },{
            R.string.question_kaeya_15_1,
            R.string.question_kaeya_15_2,
            R.string.question_kaeya_15_3,
            R.string.question_kaeya_15_4
    },{
            R.string.question_kaeya_16_1,
            R.string.question_kaeya_16_2,
            R.string.question_kaeya_16_3,
            R.string.question_kaeya_16_4
    },{
            R.string.question_kaeya_17_1,
            R.string.question_kaeya_17_2,
            R.string.question_kaeya_17_3,
            R.string.question_kaeya_17_4
    }};

    // Noelle_______________________________________________________
    final int[] questions_noelle = {
            R.string.question_noelle_1,
            R.string.question_noelle_2,
            R.string.question_noelle_3,
            R.string.question_noelle_4,
            R.string.question_noelle_5,
            R.string.question_noelle_6,
            R.string.question_noelle_7,
            R.string.question_noelle_8,
            R.string.question_noelle_9,
            R.string.question_noelle_10,
            R.string.question_noelle_11,
            R.string.question_noelle_12,
            R.string.question_noelle_13,
            R.string.question_noelle_14,
            R.string.question_noelle_15,
            R.string.question_noelle_16,
            R.string.question_noelle_17
    };

    final int[][] answers_noelle = {{
            R.string.question_noelle_1_1,
            R.string.question_noelle_1_2,
            R.string.question_noelle_1_3,
            R.string.question_noelle_1_4
    },{
            R.string.question_noelle_2_1,
            R.string.question_noelle_2_2,
            R.string.question_noelle_2_3,
            R.string.question_noelle_2_4
    },{
            R.string.question_noelle_3_1,
            R.string.question_noelle_3_2,
            R.string.question_noelle_3_3,
            R.string.question_noelle_3_4
    },{
            R.string.question_noelle_4_1,
            R.string.question_noelle_4_2,
            R.string.question_noelle_4_3,
            R.string.question_noelle_4_4
    },{
            R.string.question_noelle_5_1,
            R.string.question_noelle_5_2,
            R.string.question_noelle_5_3,
            R.string.question_noelle_5_4
    },{
            R.string.question_noelle_6_1,
            R.string.question_noelle_6_2,
            R.string.question_noelle_6_3,
            R.string.question_noelle_6_4
    },{
            R.string.question_noelle_7_1,
            R.string.question_noelle_7_2,
            R.string.question_noelle_7_3,
            R.string.question_noelle_7_4
    },{
            R.string.question_noelle_8_1,
            R.string.question_noelle_8_2,
            R.string.question_noelle_8_3,
            R.string.question_noelle_8_4
    },{
            R.string.question_noelle_9_1,
            R.string.question_noelle_9_2,
            R.string.question_noelle_9_3,
            R.string.question_noelle_9_4
    },{
            R.string.question_noelle_10_1,
            R.string.question_noelle_10_2,
            R.string.question_noelle_10_3,
            R.string.question_noelle_10_4
    },{
            R.string.question_noelle_11_1,
            R.string.question_noelle_11_2,
            R.string.question_noelle_11_3,
            R.string.question_noelle_11_4
    },{
            R.string.question_noelle_12_1,
            R.string.question_noelle_12_2,
            R.string.question_noelle_12_3,
            R.string.question_noelle_12_4
    },{
            R.string.question_noelle_13_1,
            R.string.question_noelle_13_2,
            R.string.question_noelle_13_3,
            R.string.question_noelle_13_4
    },{
            R.string.question_noelle_14_1,
            R.string.question_noelle_14_2,
            R.string.question_noelle_14_3,
            R.string.question_noelle_14_4
    },{
            R.string.question_noelle_15_1,
            R.string.question_noelle_15_2,
            R.string.question_noelle_15_3,
            R.string.question_noelle_15_4
    },{
            R.string.question_noelle_16_1,
            R.string.question_noelle_16_2,
            R.string.question_noelle_16_3,
            R.string.question_noelle_16_4
    },{
            R.string.question_noelle_17_1,
            R.string.question_noelle_17_2,
            R.string.question_noelle_17_3,
            R.string.question_noelle_17_4
    }};

    // Jean_______________________________________________________
    final int[] questions_jean = {
            R.string.question_jean_1,
            R.string.question_jean_2,
            R.string.question_jean_3,
            R.string.question_jean_4,
            R.string.question_jean_5,
            R.string.question_jean_6,
            R.string.question_jean_7,
            R.string.question_jean_8,
            R.string.question_jean_9,
            R.string.question_jean_10,
            R.string.question_jean_11,
            R.string.question_jean_12,
            R.string.question_jean_13,
            R.string.question_jean_14,
            R.string.question_jean_15,
            R.string.question_jean_16,
            R.string.question_jean_17
    };

    final int[][] answers_jean = {{
            R.string.question_jean_1_1,
            R.string.question_jean_1_2,
            R.string.question_jean_1_3,
            R.string.question_jean_1_4
    },{
            R.string.question_jean_2_1,
            R.string.question_jean_2_2,
            R.string.question_jean_2_3,
            R.string.question_jean_2_4
    },{
            R.string.question_jean_3_1,
            R.string.question_jean_3_2,
            R.string.question_jean_3_3,
            R.string.question_jean_3_4
    },{
            R.string.question_jean_4_1,
            R.string.question_jean_4_2,
            R.string.question_jean_4_3,
            R.string.question_jean_4_4
    },{
            R.string.question_jean_5_1,
            R.string.question_jean_5_2,
            R.string.question_jean_5_3,
            R.string.question_jean_5_4
    },{
            R.string.question_jean_6_1,
            R.string.question_jean_6_2,
            R.string.question_jean_6_3,
            R.string.question_jean_6_4
    },{
            R.string.question_jean_7_1,
            R.string.question_jean_7_2,
            R.string.question_jean_7_3,
            R.string.question_jean_7_4
    },{
            R.string.question_jean_8_1,
            R.string.question_jean_8_2,
            R.string.question_jean_8_3,
            R.string.question_jean_8_4
    },{
            R.string.question_jean_9_1,
            R.string.question_jean_9_2,
            R.string.question_jean_9_3,
            R.string.question_jean_9_4
    },{
            R.string.question_jean_10_1,
            R.string.question_jean_10_2,
            R.string.question_jean_10_3,
            R.string.question_jean_10_4
    },{
            R.string.question_jean_11_1,
            R.string.question_jean_11_2,
            R.string.question_jean_11_3,
            R.string.question_jean_11_4
    },{
            R.string.question_jean_12_1,
            R.string.question_jean_12_2,
            R.string.question_jean_12_3,
            R.string.question_jean_12_4
    },{
            R.string.question_jean_13_1,
            R.string.question_jean_13_2,
            R.string.question_jean_13_3,
            R.string.question_jean_13_4
    },{
            R.string.question_jean_14_1,
            R.string.question_jean_14_2,
            R.string.question_jean_14_3,
            R.string.question_jean_14_4
    },{
            R.string.question_jean_15_1,
            R.string.question_jean_15_2,
            R.string.question_jean_15_3,
            R.string.question_jean_15_4
    },{
            R.string.question_jean_16_1,
            R.string.question_jean_16_2,
            R.string.question_jean_16_3,
            R.string.question_jean_16_4
    },{
            R.string.question_jean_17_1,
            R.string.question_jean_17_2,
            R.string.question_jean_17_3,
            R.string.question_jean_17_4
    }};

    // Mona_______________________________________________________
    final int[] questions_mona = {
            R.string.question_mona_1,
            R.string.question_mona_2,
            R.string.question_mona_3,
            R.string.question_mona_4,
            R.string.question_mona_5,
            R.string.question_mona_6,
            R.string.question_mona_7,
            R.string.question_mona_8,
            R.string.question_mona_9,
            R.string.question_mona_10,
            R.string.question_mona_11,
            R.string.question_mona_12,
            R.string.question_mona_13,
            R.string.question_mona_14,
            R.string.question_mona_15,
            R.string.question_mona_16,
            R.string.question_mona_17
    };

    final int[][] answers_mona = {{
            R.string.question_mona_1_1,
            R.string.question_mona_1_2,
            R.string.question_mona_1_3,
            R.string.question_mona_1_4
    },{
            R.string.question_mona_2_1,
            R.string.question_mona_2_2,
            R.string.question_mona_2_3,
            R.string.question_mona_2_4
    },{
            R.string.question_mona_3_1,
            R.string.question_mona_3_2,
            R.string.question_mona_3_3,
            R.string.question_mona_3_4
    },{
            R.string.question_mona_4_1,
            R.string.question_mona_4_2,
            R.string.question_mona_4_3,
            R.string.question_mona_4_4
    },{
            R.string.question_mona_5_1,
            R.string.question_mona_5_2,
            R.string.question_mona_5_3,
            R.string.question_mona_5_4
    },{
            R.string.question_mona_6_1,
            R.string.question_mona_6_2,
            R.string.question_mona_6_3,
            R.string.question_mona_6_4
    },{
            R.string.question_mona_7_1,
            R.string.question_mona_7_2,
            R.string.question_mona_7_3,
            R.string.question_mona_7_4
    },{
            R.string.question_mona_8_1,
            R.string.question_mona_8_2,
            R.string.question_mona_8_3,
            R.string.question_mona_8_4
    },{
            R.string.question_mona_9_1,
            R.string.question_mona_9_2,
            R.string.question_mona_9_3,
            R.string.question_mona_9_4
    },{
            R.string.question_mona_10_1,
            R.string.question_mona_10_2,
            R.string.question_mona_10_3,
            R.string.question_mona_10_4
    },{
            R.string.question_mona_11_1,
            R.string.question_mona_11_2,
            R.string.question_mona_11_3,
            R.string.question_mona_11_4
    },{
            R.string.question_mona_12_1,
            R.string.question_mona_12_2,
            R.string.question_mona_12_3,
            R.string.question_mona_12_4
    },{
            R.string.question_mona_13_1,
            R.string.question_mona_13_2,
            R.string.question_mona_13_3,
            R.string.question_mona_13_4
    },{
            R.string.question_mona_14_1,
            R.string.question_mona_14_2,
            R.string.question_mona_14_3,
            R.string.question_mona_14_4
    },{
            R.string.question_mona_15_1,
            R.string.question_mona_15_2,
            R.string.question_mona_15_3,
            R.string.question_mona_15_4
    },{
            R.string.question_mona_16_1,
            R.string.question_mona_16_2,
            R.string.question_mona_16_3,
            R.string.question_mona_16_4
    },{
            R.string.question_mona_17_1,
            R.string.question_mona_17_2,
            R.string.question_mona_17_3,
            R.string.question_mona_17_4
    }};

    // Klee_______________________________________________________
    final int[] questions_klee = {
            R.string.question_klee_1,
            R.string.question_klee_2,
            R.string.question_klee_3,
            R.string.question_klee_4,
            R.string.question_klee_5,
            R.string.question_klee_6,
            R.string.question_klee_7,
            R.string.question_klee_8,
            R.string.question_klee_9,
            R.string.question_klee_10,
            R.string.question_klee_11,
            R.string.question_klee_12,
            R.string.question_klee_13,
            R.string.question_klee_14,
            R.string.question_klee_15,
            R.string.question_klee_16,
            R.string.question_klee_17
    };

    final int[][] answers_klee = {{
            R.string.question_klee_1_1,
            R.string.question_klee_1_2,
            R.string.question_klee_1_3,
            R.string.question_klee_1_4
    },{
            R.string.question_klee_2_1,
            R.string.question_klee_2_2,
            R.string.question_klee_2_3,
            R.string.question_klee_2_4
    },{
            R.string.question_klee_3_1,
            R.string.question_klee_3_2,
            R.string.question_klee_3_3,
            R.string.question_klee_3_4
    },{
            R.string.question_klee_4_1,
            R.string.question_klee_4_2,
            R.string.question_klee_4_3,
            R.string.question_klee_4_4
    },{
            R.string.question_klee_5_1,
            R.string.question_klee_5_2,
            R.string.question_klee_5_3,
            R.string.question_klee_5_4
    },{
            R.string.question_klee_6_1,
            R.string.question_klee_6_2,
            R.string.question_klee_6_3,
            R.string.question_klee_6_4
    },{
            R.string.question_klee_7_1,
            R.string.question_klee_7_2,
            R.string.question_klee_7_3,
            R.string.question_klee_7_4
    },{
            R.string.question_klee_8_1,
            R.string.question_klee_8_2,
            R.string.question_klee_8_3,
            R.string.question_klee_8_4
    },{
            R.string.question_klee_9_1,
            R.string.question_klee_9_2,
            R.string.question_klee_9_3,
            R.string.question_klee_9_4
    },{
            R.string.question_klee_10_1,
            R.string.question_klee_10_2,
            R.string.question_klee_10_3,
            R.string.question_klee_10_4
    },{
            R.string.question_klee_11_1,
            R.string.question_klee_11_2,
            R.string.question_klee_11_3,
            R.string.question_klee_11_4
    },{
            R.string.question_klee_12_1,
            R.string.question_klee_12_2,
            R.string.question_klee_12_3,
            R.string.question_klee_12_4
    },{
            R.string.question_klee_13_1,
            R.string.question_klee_13_2,
            R.string.question_klee_13_3,
            R.string.question_klee_13_4
    },{
            R.string.question_klee_14_1,
            R.string.question_klee_14_2,
            R.string.question_klee_14_3,
            R.string.question_klee_14_4
    },{
            R.string.question_klee_15_1,
            R.string.question_klee_15_2,
            R.string.question_klee_15_3,
            R.string.question_klee_15_4
    },{
            R.string.question_klee_16_1,
            R.string.question_klee_16_2,
            R.string.question_klee_16_3,
            R.string.question_klee_16_4
    },{
            R.string.question_klee_17_1,
            R.string.question_klee_17_2,
            R.string.question_klee_17_3,
            R.string.question_klee_17_4
    }};

    // Fischl_______________________________________________________
    final int[] questions_fischl = {
            R.string.question_fischl_1,
            R.string.question_fischl_2,
            R.string.question_fischl_3,
            R.string.question_fischl_4,
            R.string.question_fischl_5,
            R.string.question_fischl_6,
            R.string.question_fischl_7,
            R.string.question_fischl_8,
            R.string.question_fischl_9,
            R.string.question_fischl_10,
            R.string.question_fischl_11,
            R.string.question_fischl_12,
            R.string.question_fischl_13,
            R.string.question_fischl_14,
            R.string.question_fischl_15,
            R.string.question_fischl_16,
            R.string.question_fischl_17
    };

    final int[][] answers_fischl = {{
            R.string.question_fischl_1_1,
            R.string.question_fischl_1_2,
            R.string.question_fischl_1_3,
            R.string.question_fischl_1_4
    },{
            R.string.question_fischl_2_1,
            R.string.question_fischl_2_2,
            R.string.question_fischl_2_3,
            R.string.question_fischl_2_4
    },{
            R.string.question_fischl_3_1,
            R.string.question_fischl_3_2,
            R.string.question_fischl_3_3,
            R.string.question_fischl_3_4
    },{
            R.string.question_fischl_4_1,
            R.string.question_fischl_4_2,
            R.string.question_fischl_4_3,
            R.string.question_fischl_4_4
    },{
            R.string.question_fischl_5_1,
            R.string.question_fischl_5_2,
            R.string.question_fischl_5_3,
            R.string.question_fischl_5_4
    },{
            R.string.question_fischl_6_1,
            R.string.question_fischl_6_2,
            R.string.question_fischl_6_3,
            R.string.question_fischl_6_4
    },{
            R.string.question_fischl_7_1,
            R.string.question_fischl_7_2,
            R.string.question_fischl_7_3,
            R.string.question_fischl_7_4
    },{
            R.string.question_fischl_8_1,
            R.string.question_fischl_8_2,
            R.string.question_fischl_8_3,
            R.string.question_fischl_8_4
    },{
            R.string.question_fischl_9_1,
            R.string.question_fischl_9_2,
            R.string.question_fischl_9_3,
            R.string.question_fischl_9_4
    },{
            R.string.question_fischl_10_1,
            R.string.question_fischl_10_2,
            R.string.question_fischl_10_3,
            R.string.question_fischl_10_4
    },{
            R.string.question_fischl_11_1,
            R.string.question_fischl_11_2,
            R.string.question_fischl_11_3,
            R.string.question_fischl_11_4
    },{
            R.string.question_fischl_12_1,
            R.string.question_fischl_12_2,
            R.string.question_fischl_12_3,
            R.string.question_fischl_12_4
    },{
            R.string.question_fischl_13_1,
            R.string.question_fischl_13_2,
            R.string.question_fischl_13_3,
            R.string.question_fischl_13_4
    },{
            R.string.question_fischl_14_1,
            R.string.question_fischl_14_2,
            R.string.question_fischl_14_3,
            R.string.question_fischl_14_4
    },{
            R.string.question_fischl_15_1,
            R.string.question_fischl_15_2,
            R.string.question_fischl_15_3,
            R.string.question_fischl_15_4
    },{
            R.string.question_fischl_16_1,
            R.string.question_fischl_16_2,
            R.string.question_fischl_16_3,
            R.string.question_fischl_16_4
    },{
            R.string.question_fischl_17_1,
            R.string.question_fischl_17_2,
            R.string.question_fischl_17_3,
            R.string.question_fischl_17_4
    }};

    // Eula_______________________________________________________
    final int[] questions_eula = {
            R.string.question_eula_1,
            R.string.question_eula_2,
            R.string.question_eula_3,
            R.string.question_eula_4,
            R.string.question_eula_5,
            R.string.question_eula_6,
            R.string.question_eula_7,
            R.string.question_eula_8,
            R.string.question_eula_9,
            R.string.question_eula_10,
            R.string.question_eula_11,
            R.string.question_eula_12,
            R.string.question_eula_13,
            R.string.question_eula_14,
            R.string.question_eula_15,
            R.string.question_eula_16,
            R.string.question_eula_17
    };

    final int[][] answers_eula = {{
            R.string.question_eula_1_1,
            R.string.question_eula_1_2,
            R.string.question_eula_1_3,
            R.string.question_eula_1_4
    },{
            R.string.question_eula_2_1,
            R.string.question_eula_2_2,
            R.string.question_eula_2_3,
            R.string.question_eula_2_4
    },{
            R.string.question_eula_3_1,
            R.string.question_eula_3_2,
            R.string.question_eula_3_3,
            R.string.question_eula_3_4
    },{
            R.string.question_eula_4_1,
            R.string.question_eula_4_2,
            R.string.question_eula_4_3,
            R.string.question_eula_4_4
    },{
            R.string.question_eula_5_1,
            R.string.question_eula_5_2,
            R.string.question_eula_5_3,
            R.string.question_eula_5_4
    },{
            R.string.question_eula_6_1,
            R.string.question_eula_6_2,
            R.string.question_eula_6_3,
            R.string.question_eula_6_4
    },{
            R.string.question_eula_7_1,
            R.string.question_eula_7_2,
            R.string.question_eula_7_3,
            R.string.question_eula_7_4
    },{
            R.string.question_eula_8_1,
            R.string.question_eula_8_2,
            R.string.question_eula_8_3,
            R.string.question_eula_8_4
    },{
            R.string.question_eula_9_1,
            R.string.question_eula_9_2,
            R.string.question_eula_9_3,
            R.string.question_eula_9_4
    },{
            R.string.question_eula_10_1,
            R.string.question_eula_10_2,
            R.string.question_eula_10_3,
            R.string.question_eula_10_4
    },{
            R.string.question_eula_11_1,
            R.string.question_eula_11_2,
            R.string.question_eula_11_3,
            R.string.question_eula_11_4
    },{
            R.string.question_eula_12_1,
            R.string.question_eula_12_2,
            R.string.question_eula_12_3,
            R.string.question_eula_12_4
    },{
            R.string.question_eula_13_1,
            R.string.question_eula_13_2,
            R.string.question_eula_13_3,
            R.string.question_eula_13_4
    },{
            R.string.question_eula_14_1,
            R.string.question_eula_14_2,
            R.string.question_eula_14_3,
            R.string.question_eula_14_4
    },{
            R.string.question_eula_15_1,
            R.string.question_eula_15_2,
            R.string.question_eula_15_3,
            R.string.question_eula_15_4
    },{
            R.string.question_eula_16_1,
            R.string.question_eula_16_2,
            R.string.question_eula_16_3,
            R.string.question_eula_16_4
    },{
            R.string.question_eula_17_1,
            R.string.question_eula_17_2,
            R.string.question_eula_17_3,
            R.string.question_eula_17_4
    }};

    // Albedo_______________________________________________________
    final int[] questions_albedo = {
            R.string.question_albedo_1,
            R.string.question_albedo_2,
            R.string.question_albedo_3,
            R.string.question_albedo_4,
            R.string.question_albedo_5,
            R.string.question_albedo_6,
            R.string.question_albedo_7,
            R.string.question_albedo_8,
            R.string.question_albedo_9,
            R.string.question_albedo_10,
            R.string.question_albedo_11,
            R.string.question_albedo_12,
            R.string.question_albedo_13,
            R.string.question_albedo_14,
            R.string.question_albedo_15,
            R.string.question_albedo_16,
            R.string.question_albedo_17
    };

    final int[][] answers_albedo = {{
            R.string.question_albedo_1_1,
            R.string.question_albedo_1_2,
            R.string.question_albedo_1_3,
            R.string.question_albedo_1_4
    },{
            R.string.question_albedo_2_1,
            R.string.question_albedo_2_2,
            R.string.question_albedo_2_3,
            R.string.question_albedo_2_4
    },{
            R.string.question_albedo_3_1,
            R.string.question_albedo_3_2,
            R.string.question_albedo_3_3,
            R.string.question_albedo_3_4
    },{
            R.string.question_albedo_4_1,
            R.string.question_albedo_4_2,
            R.string.question_albedo_4_3,
            R.string.question_albedo_4_4
    },{
            R.string.question_albedo_5_1,
            R.string.question_albedo_5_2,
            R.string.question_albedo_5_3,
            R.string.question_albedo_5_4
    },{
            R.string.question_albedo_6_1,
            R.string.question_albedo_6_2,
            R.string.question_albedo_6_3,
            R.string.question_albedo_6_4
    },{
            R.string.question_albedo_7_1,
            R.string.question_albedo_7_2,
            R.string.question_albedo_7_3,
            R.string.question_albedo_7_4
    },{
            R.string.question_albedo_8_1,
            R.string.question_albedo_8_2,
            R.string.question_albedo_8_3,
            R.string.question_albedo_8_4
    },{
            R.string.question_albedo_9_1,
            R.string.question_albedo_9_2,
            R.string.question_albedo_9_3,
            R.string.question_albedo_9_4
    },{
            R.string.question_albedo_10_1,
            R.string.question_albedo_10_2,
            R.string.question_albedo_10_3,
            R.string.question_albedo_10_4
    },{
            R.string.question_albedo_11_1,
            R.string.question_albedo_11_2,
            R.string.question_albedo_11_3,
            R.string.question_albedo_11_4
    },{
            R.string.question_albedo_12_1,
            R.string.question_albedo_12_2,
            R.string.question_albedo_12_3,
            R.string.question_albedo_12_4
    },{
            R.string.question_albedo_13_1,
            R.string.question_albedo_13_2,
            R.string.question_albedo_13_3,
            R.string.question_albedo_13_4
    },{
            R.string.question_albedo_14_1,
            R.string.question_albedo_14_2,
            R.string.question_albedo_14_3,
            R.string.question_albedo_14_4
    },{
            R.string.question_albedo_15_1,
            R.string.question_albedo_15_2,
            R.string.question_albedo_15_3,
            R.string.question_albedo_15_4
    },{
            R.string.question_albedo_16_1,
            R.string.question_albedo_16_2,
            R.string.question_albedo_16_3,
            R.string.question_albedo_16_4
    },{
            R.string.question_albedo_17_1,
            R.string.question_albedo_17_2,
            R.string.question_albedo_17_3,
            R.string.question_albedo_17_4
    }};

    // Sucrose_______________________________________________________
    final int[] questions_sucrose = {
            R.string.question_sucrose_1,
            R.string.question_sucrose_2,
            R.string.question_sucrose_3,
            R.string.question_sucrose_4,
            R.string.question_sucrose_5,
            R.string.question_sucrose_6,
            R.string.question_sucrose_7,
            R.string.question_sucrose_8,
            R.string.question_sucrose_9,
            R.string.question_sucrose_10,
            R.string.question_sucrose_11,
            R.string.question_sucrose_12,
            R.string.question_sucrose_13,
            R.string.question_sucrose_14,
            R.string.question_sucrose_15,
            R.string.question_sucrose_16,
            R.string.question_sucrose_17
    };

    final int[][] answers_sucrose = {{
            R.string.question_sucrose_1_1,
            R.string.question_sucrose_1_2,
            R.string.question_sucrose_1_3,
            R.string.question_sucrose_1_4
    },{
            R.string.question_sucrose_2_1,
            R.string.question_sucrose_2_2,
            R.string.question_sucrose_2_3,
            R.string.question_sucrose_2_4
    },{
            R.string.question_sucrose_3_1,
            R.string.question_sucrose_3_2,
            R.string.question_sucrose_3_3,
            R.string.question_sucrose_3_4
    },{
            R.string.question_sucrose_4_1,
            R.string.question_sucrose_4_2,
            R.string.question_sucrose_4_3,
            R.string.question_sucrose_4_4
    },{
            R.string.question_sucrose_5_1,
            R.string.question_sucrose_5_2,
            R.string.question_sucrose_5_3,
            R.string.question_sucrose_5_4
    },{
            R.string.question_sucrose_6_1,
            R.string.question_sucrose_6_2,
            R.string.question_sucrose_6_3,
            R.string.question_sucrose_6_4
    },{
            R.string.question_sucrose_7_1,
            R.string.question_sucrose_7_2,
            R.string.question_sucrose_7_3,
            R.string.question_sucrose_7_4
    },{
            R.string.question_sucrose_8_1,
            R.string.question_sucrose_8_2,
            R.string.question_sucrose_8_3,
            R.string.question_sucrose_8_4
    },{
            R.string.question_sucrose_9_1,
            R.string.question_sucrose_9_2,
            R.string.question_sucrose_9_3,
            R.string.question_sucrose_9_4
    },{
            R.string.question_sucrose_10_1,
            R.string.question_sucrose_10_2,
            R.string.question_sucrose_10_3,
            R.string.question_sucrose_10_4
    },{
            R.string.question_sucrose_11_1,
            R.string.question_sucrose_11_2,
            R.string.question_sucrose_11_3,
            R.string.question_sucrose_11_4
    },{
            R.string.question_sucrose_12_1,
            R.string.question_sucrose_12_2,
            R.string.question_sucrose_12_3,
            R.string.question_sucrose_12_4
    },{
            R.string.question_sucrose_13_1,
            R.string.question_sucrose_13_2,
            R.string.question_sucrose_13_3,
            R.string.question_sucrose_13_4
    },{
            R.string.question_sucrose_14_1,
            R.string.question_sucrose_14_2,
            R.string.question_sucrose_14_3,
            R.string.question_sucrose_14_4
    },{
            R.string.question_sucrose_15_1,
            R.string.question_sucrose_15_2,
            R.string.question_sucrose_15_3,
            R.string.question_sucrose_15_4
    },{
            R.string.question_sucrose_16_1,
            R.string.question_sucrose_16_2,
            R.string.question_sucrose_16_3,
            R.string.question_sucrose_16_4
    },{
            R.string.question_sucrose_17_1,
            R.string.question_sucrose_17_2,
            R.string.question_sucrose_17_3,
            R.string.question_sucrose_17_4
    }};

    // Amber_______________________________________________________
    final int[] questions_amber = {
            R.string.question_amber_1,
            R.string.question_amber_2,
            R.string.question_amber_3,
            R.string.question_amber_4,
            R.string.question_amber_5,
            R.string.question_amber_6,
            R.string.question_amber_7,
            R.string.question_amber_8,
            R.string.question_amber_9,
            R.string.question_amber_10,
            R.string.question_amber_11,
            R.string.question_amber_12,
            R.string.question_amber_13,
            R.string.question_amber_14,
            R.string.question_amber_15,
            R.string.question_amber_16,
            R.string.question_amber_17
    };

    final int[][] answers_amber = {{
            R.string.question_amber_1_1,
            R.string.question_amber_1_2,
            R.string.question_amber_1_3,
            R.string.question_amber_1_4
    },{
            R.string.question_amber_2_1,
            R.string.question_amber_2_2,
            R.string.question_amber_2_3,
            R.string.question_amber_2_4
    },{
            R.string.question_amber_3_1,
            R.string.question_amber_3_2,
            R.string.question_amber_3_3,
            R.string.question_amber_3_4
    },{
            R.string.question_amber_4_1,
            R.string.question_amber_4_2,
            R.string.question_amber_4_3,
            R.string.question_amber_4_4
    },{
            R.string.question_amber_5_1,
            R.string.question_amber_5_2,
            R.string.question_amber_5_3,
            R.string.question_amber_5_4
    },{
            R.string.question_amber_6_1,
            R.string.question_amber_6_2,
            R.string.question_amber_6_3,
            R.string.question_amber_6_4
    },{
            R.string.question_amber_7_1,
            R.string.question_amber_7_2,
            R.string.question_amber_7_3,
            R.string.question_amber_7_4
    },{
            R.string.question_amber_8_1,
            R.string.question_amber_8_2,
            R.string.question_amber_8_3,
            R.string.question_amber_8_4
    },{
            R.string.question_amber_9_1,
            R.string.question_amber_9_2,
            R.string.question_amber_9_3,
            R.string.question_amber_9_4
    },{
            R.string.question_amber_10_1,
            R.string.question_amber_10_2,
            R.string.question_amber_10_3,
            R.string.question_amber_10_4
    },{
            R.string.question_amber_11_1,
            R.string.question_amber_11_2,
            R.string.question_amber_11_3,
            R.string.question_amber_11_4
    },{
            R.string.question_amber_12_1,
            R.string.question_amber_12_2,
            R.string.question_amber_12_3,
            R.string.question_amber_12_4
    },{
            R.string.question_amber_13_1,
            R.string.question_amber_13_2,
            R.string.question_amber_13_3,
            R.string.question_amber_13_4
    },{
            R.string.question_amber_14_1,
            R.string.question_amber_14_2,
            R.string.question_amber_14_3,
            R.string.question_amber_14_4
    },{
            R.string.question_amber_15_1,
            R.string.question_amber_15_2,
            R.string.question_amber_15_3,
            R.string.question_amber_15_4
    },{
            R.string.question_amber_16_1,
            R.string.question_amber_16_2,
            R.string.question_amber_16_3,
            R.string.question_amber_16_4
    },{
            R.string.question_amber_17_1,
            R.string.question_amber_17_2,
            R.string.question_amber_17_3,
            R.string.question_amber_17_4
    }};

    // Razor_______________________________________________________
    final int[] questions_razor = {
            R.string.question_razor_1,
            R.string.question_razor_2,
            R.string.question_razor_3,
            R.string.question_razor_4,
            R.string.question_razor_5,
            R.string.question_razor_6,
            R.string.question_razor_7,
            R.string.question_razor_8,
            R.string.question_razor_9,
            R.string.question_razor_10,
            R.string.question_razor_11,
            R.string.question_razor_12,
            R.string.question_razor_13,
            R.string.question_razor_14,
            R.string.question_razor_15,
            R.string.question_razor_16,
            R.string.question_razor_17
    };

    final int[][] answers_razor = {{
            R.string.question_razor_1_1,
            R.string.question_razor_1_2,
            R.string.question_razor_1_3,
            R.string.question_razor_1_4
    },{
            R.string.question_razor_2_1,
            R.string.question_razor_2_2,
            R.string.question_razor_2_3,
            R.string.question_razor_2_4
    },{
            R.string.question_razor_3_1,
            R.string.question_razor_3_2,
            R.string.question_razor_3_3,
            R.string.question_razor_3_4
    },{
            R.string.question_razor_4_1,
            R.string.question_razor_4_2,
            R.string.question_razor_4_3,
            R.string.question_razor_4_4
    },{
            R.string.question_razor_5_1,
            R.string.question_razor_5_2,
            R.string.question_razor_5_3,
            R.string.question_razor_5_4
    },{
            R.string.question_razor_6_1,
            R.string.question_razor_6_2,
            R.string.question_razor_6_3,
            R.string.question_razor_6_4
    },{
            R.string.question_razor_7_1,
            R.string.question_razor_7_2,
            R.string.question_razor_7_3,
            R.string.question_razor_7_4
    },{
            R.string.question_razor_8_1,
            R.string.question_razor_8_2,
            R.string.question_razor_8_3,
            R.string.question_razor_8_4
    },{
            R.string.question_razor_9_1,
            R.string.question_razor_9_2,
            R.string.question_razor_9_3,
            R.string.question_razor_9_4
    },{
            R.string.question_razor_10_1,
            R.string.question_razor_10_2,
            R.string.question_razor_10_3,
            R.string.question_razor_10_4
    },{
            R.string.question_razor_11_1,
            R.string.question_razor_11_2,
            R.string.question_razor_11_3,
            R.string.question_razor_11_4
    },{
            R.string.question_razor_12_1,
            R.string.question_razor_12_2,
            R.string.question_razor_12_3,
            R.string.question_razor_12_4
    },{
            R.string.question_razor_13_1,
            R.string.question_razor_13_2,
            R.string.question_razor_13_3,
            R.string.question_razor_13_4
    },{
            R.string.question_razor_14_1,
            R.string.question_razor_14_2,
            R.string.question_razor_14_3,
            R.string.question_razor_14_4
    },{
            R.string.question_razor_15_1,
            R.string.question_razor_15_2,
            R.string.question_razor_15_3,
            R.string.question_razor_15_4
    },{
            R.string.question_razor_16_1,
            R.string.question_razor_16_2,
            R.string.question_razor_16_3,
            R.string.question_razor_16_4
    },{
            R.string.question_razor_17_1,
            R.string.question_razor_17_2,
            R.string.question_razor_17_3,
            R.string.question_razor_17_4
    }};

    // Rosaria_______________________________________________________
    final int[] questions_rosaria = {
            R.string.question_rosaria_1,
            R.string.question_rosaria_2,
            R.string.question_rosaria_3,
            R.string.question_rosaria_4,
            R.string.question_rosaria_5,
            R.string.question_rosaria_6,
            R.string.question_rosaria_7,
            R.string.question_rosaria_8,
            R.string.question_rosaria_9,
            R.string.question_rosaria_10,
            R.string.question_rosaria_11,
            R.string.question_rosaria_12,
            R.string.question_rosaria_13,
            R.string.question_rosaria_14,
            R.string.question_rosaria_15,
            R.string.question_rosaria_16,
            R.string.question_rosaria_17
    };

    final int[][] answers_rosaria = {{
            R.string.question_rosaria_1_1,
            R.string.question_rosaria_1_2,
            R.string.question_rosaria_1_3,
            R.string.question_rosaria_1_4
    },{
            R.string.question_rosaria_2_1,
            R.string.question_rosaria_2_2,
            R.string.question_rosaria_2_3,
            R.string.question_rosaria_2_4
    },{
            R.string.question_rosaria_3_1,
            R.string.question_rosaria_3_2,
            R.string.question_rosaria_3_3,
            R.string.question_rosaria_3_4
    },{
            R.string.question_rosaria_4_1,
            R.string.question_rosaria_4_2,
            R.string.question_rosaria_4_3,
            R.string.question_rosaria_4_4
    },{
            R.string.question_rosaria_5_1,
            R.string.question_rosaria_5_2,
            R.string.question_rosaria_5_3,
            R.string.question_rosaria_5_4
    },{
            R.string.question_rosaria_6_1,
            R.string.question_rosaria_6_2,
            R.string.question_rosaria_6_3,
            R.string.question_rosaria_6_4
    },{
            R.string.question_rosaria_7_1,
            R.string.question_rosaria_7_2,
            R.string.question_rosaria_7_3,
            R.string.question_rosaria_7_4
    },{
            R.string.question_rosaria_8_1,
            R.string.question_rosaria_8_2,
            R.string.question_rosaria_8_3,
            R.string.question_rosaria_8_4
    },{
            R.string.question_rosaria_9_1,
            R.string.question_rosaria_9_2,
            R.string.question_rosaria_9_3,
            R.string.question_rosaria_9_4
    },{
            R.string.question_rosaria_10_1,
            R.string.question_rosaria_10_2,
            R.string.question_rosaria_10_3,
            R.string.question_rosaria_10_4
    },{
            R.string.question_rosaria_11_1,
            R.string.question_rosaria_11_2,
            R.string.question_rosaria_11_3,
            R.string.question_rosaria_11_4
    },{
            R.string.question_rosaria_12_1,
            R.string.question_rosaria_12_2,
            R.string.question_rosaria_12_3,
            R.string.question_rosaria_12_4
    },{
            R.string.question_rosaria_13_1,
            R.string.question_rosaria_13_2,
            R.string.question_rosaria_13_3,
            R.string.question_rosaria_13_4
    },{
            R.string.question_rosaria_14_1,
            R.string.question_rosaria_14_2,
            R.string.question_rosaria_14_3,
            R.string.question_rosaria_14_4
    },{
            R.string.question_rosaria_15_1,
            R.string.question_rosaria_15_2,
            R.string.question_rosaria_15_3,
            R.string.question_rosaria_15_4
    },{
            R.string.question_rosaria_16_1,
            R.string.question_rosaria_16_2,
            R.string.question_rosaria_16_3,
            R.string.question_rosaria_16_4
    },{
            R.string.question_rosaria_17_1,
            R.string.question_rosaria_17_2,
            R.string.question_rosaria_17_3,
            R.string.question_rosaria_17_4
    }};

    // Bennett_______________________________________________________
    final int[] questions_bennett = {
            R.string.question_bennett_1,
            R.string.question_bennett_2,
            R.string.question_bennett_3,
            R.string.question_bennett_4,
            R.string.question_bennett_5,
            R.string.question_bennett_6,
            R.string.question_bennett_7,
            R.string.question_bennett_8,
            R.string.question_bennett_9,
            R.string.question_bennett_10,
            R.string.question_bennett_11,
            R.string.question_bennett_12,
            R.string.question_bennett_13,
            R.string.question_bennett_14,
            R.string.question_bennett_15,
            R.string.question_bennett_16,
            R.string.question_bennett_17
    };

    final int[][] answers_bennett = {{
            R.string.question_bennett_1_1,
            R.string.question_bennett_1_2,
            R.string.question_bennett_1_3,
            R.string.question_bennett_1_4
    },{
            R.string.question_bennett_2_1,
            R.string.question_bennett_2_2,
            R.string.question_bennett_2_3,
            R.string.question_bennett_2_4
    },{
            R.string.question_bennett_3_1,
            R.string.question_bennett_3_2,
            R.string.question_bennett_3_3,
            R.string.question_bennett_3_4
    },{
            R.string.question_bennett_4_1,
            R.string.question_bennett_4_2,
            R.string.question_bennett_4_3,
            R.string.question_bennett_4_4
    },{
            R.string.question_bennett_5_1,
            R.string.question_bennett_5_2,
            R.string.question_bennett_5_3,
            R.string.question_bennett_5_4
    },{
            R.string.question_bennett_6_1,
            R.string.question_bennett_6_2,
            R.string.question_bennett_6_3,
            R.string.question_bennett_6_4
    },{
            R.string.question_bennett_7_1,
            R.string.question_bennett_7_2,
            R.string.question_bennett_7_3,
            R.string.question_bennett_7_4
    },{
            R.string.question_bennett_8_1,
            R.string.question_bennett_8_2,
            R.string.question_bennett_8_3,
            R.string.question_bennett_8_4
    },{
            R.string.question_bennett_9_1,
            R.string.question_bennett_9_2,
            R.string.question_bennett_9_3,
            R.string.question_bennett_9_4
    },{
            R.string.question_bennett_10_1,
            R.string.question_bennett_10_2,
            R.string.question_bennett_10_3,
            R.string.question_bennett_10_4
    },{
            R.string.question_bennett_11_1,
            R.string.question_bennett_11_2,
            R.string.question_bennett_11_3,
            R.string.question_bennett_11_4
    },{
            R.string.question_bennett_12_1,
            R.string.question_bennett_12_2,
            R.string.question_bennett_12_3,
            R.string.question_bennett_12_4
    },{
            R.string.question_bennett_13_1,
            R.string.question_bennett_13_2,
            R.string.question_bennett_13_3,
            R.string.question_bennett_13_4
    },{
            R.string.question_bennett_14_1,
            R.string.question_bennett_14_2,
            R.string.question_bennett_14_3,
            R.string.question_bennett_14_4
    },{
            R.string.question_bennett_15_1,
            R.string.question_bennett_15_2,
            R.string.question_bennett_15_3,
            R.string.question_bennett_15_4
    },{
            R.string.question_bennett_16_1,
            R.string.question_bennett_16_2,
            R.string.question_bennett_16_3,
            R.string.question_bennett_16_4
    },{
            R.string.question_bennett_17_1,
            R.string.question_bennett_17_2,
            R.string.question_bennett_17_3,
            R.string.question_bennett_17_4
    }};

    // Diona_______________________________________________________
    final int[] questions_diona = {
            R.string.question_diona_1,
            R.string.question_diona_2,
            R.string.question_diona_3,
            R.string.question_diona_4,
            R.string.question_diona_5,
            R.string.question_diona_6,
            R.string.question_diona_7,
            R.string.question_diona_8,
            R.string.question_diona_9,
            R.string.question_diona_10,
            R.string.question_diona_11,
            R.string.question_diona_12,
            R.string.question_diona_13,
            R.string.question_diona_14,
            R.string.question_diona_15,
            R.string.question_diona_16,
            R.string.question_diona_17
    };

    final int[][] answers_diona = {{
            R.string.question_diona_1_1,
            R.string.question_diona_1_2,
            R.string.question_diona_1_3,
            R.string.question_diona_1_4
    },{
            R.string.question_diona_2_1,
            R.string.question_diona_2_2,
            R.string.question_diona_2_3,
            R.string.question_diona_2_4
    },{
            R.string.question_diona_3_1,
            R.string.question_diona_3_2,
            R.string.question_diona_3_3,
            R.string.question_diona_3_4
    },{
            R.string.question_diona_4_1,
            R.string.question_diona_4_2,
            R.string.question_diona_4_3,
            R.string.question_diona_4_4
    },{
            R.string.question_diona_5_1,
            R.string.question_diona_5_2,
            R.string.question_diona_5_3,
            R.string.question_diona_5_4
    },{
            R.string.question_diona_6_1,
            R.string.question_diona_6_2,
            R.string.question_diona_6_3,
            R.string.question_diona_6_4
    },{
            R.string.question_diona_7_1,
            R.string.question_diona_7_2,
            R.string.question_diona_7_3,
            R.string.question_diona_7_4
    },{
            R.string.question_diona_8_1,
            R.string.question_diona_8_2,
            R.string.question_diona_8_3,
            R.string.question_diona_8_4
    },{
            R.string.question_diona_9_1,
            R.string.question_diona_9_2,
            R.string.question_diona_9_3,
            R.string.question_diona_9_4
    },{
            R.string.question_diona_10_1,
            R.string.question_diona_10_2,
            R.string.question_diona_10_3,
            R.string.question_diona_10_4
    },{
            R.string.question_diona_11_1,
            R.string.question_diona_11_2,
            R.string.question_diona_11_3,
            R.string.question_diona_11_4
    },{
            R.string.question_diona_12_1,
            R.string.question_diona_12_2,
            R.string.question_diona_12_3,
            R.string.question_diona_12_4
    },{
            R.string.question_diona_13_1,
            R.string.question_diona_13_2,
            R.string.question_diona_13_3,
            R.string.question_diona_13_4
    },{
            R.string.question_diona_14_1,
            R.string.question_diona_14_2,
            R.string.question_diona_14_3,
            R.string.question_diona_14_4
    },{
            R.string.question_diona_15_1,
            R.string.question_diona_15_2,
            R.string.question_diona_15_3,
            R.string.question_diona_15_4
    },{
            R.string.question_diona_16_1,
            R.string.question_diona_16_2,
            R.string.question_diona_16_3,
            R.string.question_diona_16_4
    },{
            R.string.question_diona_17_1,
            R.string.question_diona_17_2,
            R.string.question_diona_17_3,
            R.string.question_diona_17_4
    }};

    //_____________________________________________________________
    // Diona_______________________________________________________
    final int[] questions_qiqi = {
            R.string.question_qiqi_1,
            R.string.question_qiqi_2,
            R.string.question_qiqi_3,
            R.string.question_qiqi_4,
            R.string.question_qiqi_5,
            R.string.question_qiqi_6,
            R.string.question_qiqi_7,
            R.string.question_qiqi_8,
            R.string.question_qiqi_9,
            R.string.question_qiqi_10,
            R.string.question_qiqi_11,
            R.string.question_qiqi_12,
            R.string.question_qiqi_13,
            R.string.question_qiqi_14,
            R.string.question_qiqi_15,
            R.string.question_qiqi_16,
            R.string.question_qiqi_17
    };

    final int[][] answers_qiqi = {{
            R.string.question_qiqi_1_1,
            R.string.question_qiqi_1_2,
            R.string.question_qiqi_1_3,
            R.string.question_qiqi_1_4
    },{
            R.string.question_qiqi_2_1,
            R.string.question_qiqi_2_2,
            R.string.question_qiqi_2_3,
            R.string.question_qiqi_2_4
    },{
            R.string.question_qiqi_3_1,
            R.string.question_qiqi_3_2,
            R.string.question_qiqi_3_3,
            R.string.question_qiqi_3_4
    },{
            R.string.question_qiqi_4_1,
            R.string.question_qiqi_4_2,
            R.string.question_qiqi_4_3,
            R.string.question_qiqi_4_4
    },{
            R.string.question_qiqi_5_1,
            R.string.question_qiqi_5_2,
            R.string.question_qiqi_5_3,
            R.string.question_qiqi_5_4
    },{
            R.string.question_qiqi_6_1,
            R.string.question_qiqi_6_2,
            R.string.question_qiqi_6_3,
            R.string.question_qiqi_6_4
    },{
            R.string.question_qiqi_7_1,
            R.string.question_qiqi_7_2,
            R.string.question_qiqi_7_3,
            R.string.question_qiqi_7_4
    },{
            R.string.question_qiqi_8_1,
            R.string.question_qiqi_8_2,
            R.string.question_qiqi_8_3,
            R.string.question_qiqi_8_4
    },{
            R.string.question_qiqi_9_1,
            R.string.question_qiqi_9_2,
            R.string.question_qiqi_9_3,
            R.string.question_qiqi_9_4
    },{
            R.string.question_qiqi_10_1,
            R.string.question_qiqi_10_2,
            R.string.question_qiqi_10_3,
            R.string.question_qiqi_10_4
    },{
            R.string.question_qiqi_11_1,
            R.string.question_qiqi_11_2,
            R.string.question_qiqi_11_3,
            R.string.question_qiqi_11_4
    },{
            R.string.question_qiqi_12_1,
            R.string.question_qiqi_12_2,
            R.string.question_qiqi_12_3,
            R.string.question_qiqi_12_4
    },{
            R.string.question_qiqi_13_1,
            R.string.question_qiqi_13_2,
            R.string.question_qiqi_13_3,
            R.string.question_qiqi_13_4
    },{
            R.string.question_qiqi_14_1,
            R.string.question_qiqi_14_2,
            R.string.question_qiqi_14_3,
            R.string.question_qiqi_14_4
    },{
            R.string.question_qiqi_15_1,
            R.string.question_qiqi_15_2,
            R.string.question_qiqi_15_3,
            R.string.question_qiqi_15_4
    },{
            R.string.question_qiqi_16_1,
            R.string.question_qiqi_16_2,
            R.string.question_qiqi_16_3,
            R.string.question_qiqi_16_4
    },{
            R.string.question_qiqi_17_1,
            R.string.question_qiqi_17_2,
            R.string.question_qiqi_17_3,
            R.string.question_qiqi_17_4
    }};
}
